# Site settings
title: SomeNameDevTeam
email: SomeNameDevTeam@dev.ru
description: Мы крутые ребята :)
baseurl: "/dev-blog/" # the subpath of your site, e.g. /blog/
url: "http://somenamedevteam.github.io" # the base hostname & protocol for your site
github: {repository_url: "https://github.com/SomeNameDevTeam/dev-blog"}

# Build settings
markdown: redcarpet
timezone: Europe/Moscow
