# Site settings
title: SomeNameDevTeam
email: SomeNameDevTeam@dev.ru
description: Мы крутые ребята :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://somenamedevteam.github.io/dev-blog/" # the base hostname & protocol for your site
github: {repository_url: "https://github.com/SomeNameDevTeam/dev-blog"}
safe: true
lsi: false
source: _site

# Build settings
markdown: redcarpet
timezone: Europe/Moscow
